
USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS CLAIMS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for dbt transformations on healthcare claims data';


CREATE DATABASE IF NOT EXISTS CLAIMS_DB
  COMMENT = 'Healthcare claims analytics — raw, staging, intermediate, marts';

CREATE SCHEMA IF NOT EXISTS CLAIMS_DB.RAW          COMMENT = 'Raw landed CSVs';
CREATE SCHEMA IF NOT EXISTS CLAIMS_DB.STAGING      COMMENT = 'dbt staging views';
CREATE SCHEMA IF NOT EXISTS CLAIMS_DB.INTERMEDIATE COMMENT = 'dbt intermediate models';
CREATE SCHEMA IF NOT EXISTS CLAIMS_DB.MARTS        COMMENT = 'dbt marts — facts, dims, analytics';

CREATE ROLE IF NOT EXISTS DBT_ROLE COMMENT = 'Role used by dbt to build models';

GRANT USAGE, OPERATE ON WAREHOUSE CLAIMS_WH TO ROLE DBT_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE CLAIMS_DB TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA CLAIMS_DB.RAW          TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA CLAIMS_DB.STAGING      TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA CLAIMS_DB.INTERMEDIATE TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA CLAIMS_DB.MARTS        TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA CLAIMS_DB.RAW    TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA CLAIMS_DB.RAW TO ROLE DBT_ROLE;

CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = '<<CHANGE_THIS_TO_A_STRONG_PASSWORD>>'
  LOGIN_NAME = 'DBT_USER'
  DEFAULT_WAREHOUSE = CLAIMS_WH
  DEFAULT_ROLE = DBT_ROLE
  DEFAULT_NAMESPACE = CLAIMS_DB.RAW
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for dbt';

GRANT ROLE DBT_ROLE TO USER DBT_USER;
