-- Healthcare Claims Analytics - Raw table definitions
-- Creates 8 tables matching the Synthea CSV schemas.
-- Load CSVs into these tables via Snowflake UI (Load Data) after running this.

USE ROLE ACCOUNTADMIN;
USE DATABASE CLAIMS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_PATIENTS (
  ID VARCHAR, BIRTHDATE DATE, DEATHDATE DATE, SSN VARCHAR, DRIVERS VARCHAR,
  PASSPORT VARCHAR, PREFIX VARCHAR, FIRST VARCHAR, LAST VARCHAR, SUFFIX VARCHAR,
  MAIDEN VARCHAR, MARITAL VARCHAR, RACE VARCHAR, ETHNICITY VARCHAR, GENDER VARCHAR,
  BIRTHPLACE VARCHAR, ADDRESS VARCHAR, CITY VARCHAR, STATE VARCHAR, COUNTY VARCHAR,
  ZIP VARCHAR, LAT FLOAT, LON FLOAT, HEALTHCARE_EXPENSES FLOAT, HEALTHCARE_COVERAGE FLOAT
);

CREATE OR REPLACE TABLE RAW_ENCOUNTERS (
  ID VARCHAR, "START" TIMESTAMP_NTZ, "STOP" TIMESTAMP_NTZ, PATIENT VARCHAR,
  ORGANIZATION VARCHAR, PROVIDER VARCHAR, PAYER VARCHAR, ENCOUNTERCLASS VARCHAR,
  CODE VARCHAR, DESCRIPTION VARCHAR, BASE_ENCOUNTER_COST FLOAT, TOTAL_CLAIM_COST FLOAT,
  PAYER_COVERAGE FLOAT, REASONCODE VARCHAR, REASONDESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE RAW_CLAIMS (
  ID VARCHAR, PATIENTID VARCHAR, PROVIDERID VARCHAR, PRIMARYPATIENTINSURANCEID VARCHAR,
  SECONDARYPATIENTINSURANCEID VARCHAR, DEPARTMENTID VARCHAR, PATIENTDEPARTMENTID VARCHAR,
  DIAGNOSIS1 VARCHAR, DIAGNOSIS2 VARCHAR, DIAGNOSIS3 VARCHAR, DIAGNOSIS4 VARCHAR,
  DIAGNOSIS5 VARCHAR, DIAGNOSIS6 VARCHAR, DIAGNOSIS7 VARCHAR, DIAGNOSIS8 VARCHAR,
  REFERRINGPROVIDERID VARCHAR, APPOINTMENTID VARCHAR, CURRENTILLNESSDATE TIMESTAMP_NTZ,
  SERVICEDATE TIMESTAMP_NTZ, SUPERVISINGPROVIDERID VARCHAR, STATUS1 VARCHAR,
  STATUS2 VARCHAR, STATUSP VARCHAR, OUTSTANDING1 FLOAT, OUTSTANDING2 FLOAT,
  OUTSTANDINGP FLOAT, LASTBILLEDDATE1 TIMESTAMP_NTZ, LASTBILLEDDATE2 TIMESTAMP_NTZ,
  LASTBILLEDDATEP TIMESTAMP_NTZ, HEALTHCARECLAIMTYPEID1 VARCHAR, HEALTHCARECLAIMTYPEID2 VARCHAR
);

CREATE OR REPLACE TABLE RAW_CONDITIONS (
  "START" DATE, "STOP" DATE, PATIENT VARCHAR, ENCOUNTER VARCHAR,
  CODE VARCHAR, DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE RAW_PROVIDERS (
  ID VARCHAR, ORGANIZATION VARCHAR, NAME VARCHAR, GENDER VARCHAR, SPECIALITY VARCHAR,
  ADDRESS VARCHAR, CITY VARCHAR, STATE VARCHAR, ZIP VARCHAR, LAT FLOAT, LON FLOAT,
  UTILIZATION NUMBER
);

CREATE OR REPLACE TABLE RAW_ORGANIZATIONS (
  ID VARCHAR, NAME VARCHAR, ADDRESS VARCHAR, CITY VARCHAR, STATE VARCHAR, ZIP VARCHAR,
  LAT FLOAT, LON FLOAT, PHONE VARCHAR, REVENUE FLOAT, UTILIZATION NUMBER
);

CREATE OR REPLACE TABLE RAW_PAYERS (
  ID VARCHAR, NAME VARCHAR, ADDRESS VARCHAR, CITY VARCHAR, STATE_HEADQUARTERED VARCHAR,
  ZIP VARCHAR, PHONE VARCHAR, AMOUNT_COVERED FLOAT, AMOUNT_UNCOVERED FLOAT,
  REVENUE FLOAT, COVERED_ENCOUNTERS NUMBER, UNCOVERED_ENCOUNTERS NUMBER,
  COVERED_MEDICATIONS NUMBER, UNCOVERED_MEDICATIONS NUMBER, COVERED_PROCEDURES NUMBER,
  UNCOVERED_PROCEDURES NUMBER, COVERED_IMMUNIZATIONS NUMBER, UNCOVERED_IMMUNIZATIONS NUMBER,
  UNIQUE_CUSTOMERS NUMBER, QOLS_AVG FLOAT, MEMBER_MONTHS NUMBER
);

CREATE OR REPLACE TABLE RAW_PAYER_TRANSITIONS (
  PATIENT VARCHAR, MEMBERID VARCHAR, START_YEAR TIMESTAMP_NTZ, END_YEAR TIMESTAMP_NTZ,
  PAYER VARCHAR, SECONDARY_PAYER VARCHAR, OWNERSHIP VARCHAR, OWNERNAME VARCHAR
);